SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

PLAYER_RADIUS = 20 #radius hráčovi lodi
LINE_WIDTH = 2 #šířka čar, které zobrazují loď

PLAYER_TURN_SPEED = 300 #hráč se otáčí o 300°/s
PLAYER_SPEED = 200 #rychlost 200px/s

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3
